# Generated by Django 5.1.3 on 2025-01-09 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, max_length=255)),
                ('ar_no', models.CharField(blank=True, max_length=100)),
                ('car_no', models.CharField(blank=True, max_length=20, null=True)),
                ('area', models.CharField(choices=[('IP Line 1', 'IP Line 1'), ('IP Line 2', 'IP Line 2'), ('IP-CBF', 'IP-CBF'), ('IP-ELement', 'IP-ELement'), ('IP Prep', 'IP Prep'), ('IQC', 'IQC'), ('OQC', 'OQC'), ('MID QC', 'MID QC'), ('WH', 'WH')], max_length=10)),
                ('ar_category', models.CharField(max_length=255)),
                ('abnormality', models.CharField(max_length=120)),
                ('nature_of_abnormality', models.CharField(blank=True, default=None, max_length=400)),
                ('affected_item', models.CharField(blank=True, max_length=500)),
                ('level', models.CharField(blank=True, choices=[('One', 1), ('Two', 2)], max_length=3, null=True)),
                ('created', models.CharField(blank=True, max_length=10, null=True)),
                ('detection_process', models.CharField(blank=True, max_length=500, null=True)),
                ('function', models.CharField(blank=True, max_length=10, null=True)),
                ('incharge', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('CAR CREATION', 'CAR CREATION'), ('UNDER REVIEW', 'UNDER REVIEW'), ('APPROVED', 'APPROVED'), ('IMPLEMENTATION', 'IMPLEMENTATION'), ('VALIDATION', 'VALIDATION'), ('OPEN', 'OPEN'), ('CLOSED', 'CLOSED')], max_length=14, null=True)),
                ('countermeasure', models.CharField(blank=True, max_length=255, null=True)),
                ('fanout', models.BooleanField(default=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
