# Generated by Django 5.1.3 on 2025-01-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipcategory',
            name='self_resolve_for_car',
            field=models.CharField(blank=True, choices=[('FOR CAR', 'FOR CAR'), ('SELF RESOLVE', 'SELF RESOLVE')], max_length=12, null=True),
        ),
    ]
