# Generated by Django 5.1.1 on 2025-01-03 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
