# Generated by Django 5.1.3 on 2025-01-04 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_category_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='car_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
