# Generated by Django 5.1.3 on 2025-01-09 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_category_car_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='self_resolve_for_car',
        ),
        migrations.AlterField(
            model_name='category',
            name='detection_process',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='function',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='incharge',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='level',
            field=models.CharField(blank=True, choices=[('One', 1), ('Two', 2)], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(blank=True, choices=[('CAR CREATION', 'CAR CREATION'), ('UNDER REVIEW', 'UNDER REVIEW'), ('APPROVED', 'APPROVED'), ('IMPLEMENTATION', 'IMPLEMENTATION'), ('VALIDATION', 'VALIDATION'), ('OPEN', 'OPEN'), ('CLOSED', 'CLOSED')], max_length=14, null=True),
        ),
    ]
